  
# [Choice] Node.js version: 14, 12, 10
ARG VARIANT=14
FROM mcr.microsoft.com/vscode/devcontainers/javascript-node:${VARIANT}
#FROM node:slim
RUN apt update && apt install git htop vim  libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb -y

WORKDIR /usr/app

COPY . .
RUN  sudo npm i

CMD ["npm" , "run" , "serve"]
