FROM node:alpine as build-stage

WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

FROM nginx:alpine as production-stage

#RUN apk add install git htop vim -y

EXPOSE 443
RUN mkdir /app
COPY --from=build-stage /app/dist /app
COPY  nginx/nginx.conf /etc/nginx/nginx.conf