  
# [Choice] Node.js version: 14, 12, 10
ARG VARIANT=14
FROM mcr.microsoft.com/vscode/devcontainers/javascript-node:${VARIANT}

RUN apt update && apt install git htop vim -y

WORKDIR /usr/app

COPY . .

RUN  npm i

#USER node

EXPOSE 80

CMD ["npm" , "run" , "serve"]
